/**
 * @what - WebSocket client for the Past, Live Hono relay
 * @why - Manages WS lifecycle, dispatches server messages to Nano Stores, exposes send helpers.
 *        Includes auto-retry logic for unexpected disconnects (Batch 3: session resilience).
 * @exports - connectSession, sendAudio, sendText, sendAudioEnd, disconnect
 */

import {
  $status,
  $error,
  $sessionId,
  $scenarioId,
  $topic,
  $sessionStartTime,
  $characterName,
  $inputTranscript,
  $isSpeaking,
  $activeChoices,
  $activeChoiceContext,
  $sceneImage,
  $sceneImages,
  $sceneImageLoading,
  $sceneImageFailed,
  $previewData,
  appendOutputTranscript,
  addMessage,
  replaceLastMessage,
  type StoryScriptData,
} from '../../stores/liveSession';
import { persistSession, clearPersistedSession } from './session-store';
import {
  queueAudio, clearAudioQueue, notifyModelSpeaking, suppressAudio, unsuppressAudioDebounced,
  startWebSpeechTranscription, stopWebSpeechTranscription, isWebSpeechAvailable,
} from './audio';
import { createSummaryArtifact, createSummaryFromServer } from './summary';
import { sanitizeTranscript } from './sanitize';
import {
  enqueueWords,
  flushAll,
  clearPacer,
  setPacerCallback,
  resetPacer,
  handleInputTranscription as trackInputTurn,
  finalizeInputTurn,
  getInputTranscript,
  resetInputTracking,
} from './transcript-pacer';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ConnectConfig {
  scenarioId?: string;
  topic?: string;
  voiceName?: string;
  backendWsUrl: string;
  /** Phase 2: passed to backend for post-call summary prompt context */
  characterName?: string;
  /** Phase 2: passed to backend for post-call summary prompt context */
  historicalSetting?: string;
  /** Phase 2: Clerk user ID — undefined for anonymous users, saves calls to Firestore when present */
  studentId?: string;
  /**
   * Bag-of-material generated by Flash for this character.
   * Serialized as-is into the WebSocket start message — relay validates it against StoryScript schema.
   * Absent for preset scenarios and Flash fallbacks.
   */
  storyScript?: StoryScriptData;
  /**
   * Preview ID from /session-preview — used by relay to look up pre-generated scene images.
   * Without this, show_scene falls back to on-the-fly generation (2-3s paid, 12-15s free).
   */
  previewId?: string;
}

// ─── Module state ─────────────────────────────────────────────────────────────

let ws: WebSocket | null = null;

/**
 * Retry backoff delays (ms). Max 4 attempts.
 * On unexpected disconnect, the client attempts to resume with exponential backoff
 * before escalating to error state. Resets to 0 on successful reconnect.
 */
const RETRY_DELAYS = [500, 1000, 2000, 4000];
let retryAttempt = 0;

/**
 * Last config used for connectSession — stored so retry logic can reuse the WS URL
 * without requiring the caller to re-supply it after a disconnect.
 */
let lastConfig: ConnectConfig | null = null;

/**
 * Suppress flag for ghost text after interruption.
 * When the model is interrupted, its next 1-2 transcription events are stale
 * audio that was already being spoken — we suppress them to avoid ghost messages.
 */
let suppressTranscriptionCount = 0;

/**
 * When true, Web Speech API provides user-facing chat messages.
 * Gemini's input_transcription still flows for server-side logging.
 * Falls back to false when Web Speech API is unavailable (Firefox, some mobile).
 */
let useWebSpeechForDisplay = false;

// ─── Connect ──────────────────────────────────────────────────────────────────

export function connectSession(config: ConnectConfig): void {
  if (ws && ws.readyState !== WebSocket.CLOSED) {
    ws.close();
  }

  lastConfig = config;
  retryAttempt = 0;
  suppressTranscriptionCount = 0;
  resetPacer();
  resetInputTracking();

  // Start Web Speech API for faster user-facing chat display when available
  stopWebSpeechTranscription(); // clean up any previous session
  useWebSpeechForDisplay = isWebSpeechAvailable();
  if (useWebSpeechForDisplay) {
    startWebSpeechTranscription((text) => {
      // Web Speech result: show immediately in chat, dismiss choices, track turn
      trackInputTurn(text);
      finalizeInputTurn();
      $inputTranscript.set(getInputTranscript());
      addMessage('YOU', text);
      if ($activeChoices.get()) $activeChoices.set(null);
    });
  }

  // Wire pacer: each dripped word goes into the chat log as the character
  setPacerCallback((word) => {
    const sender = $characterName.get();
    addMessage(sender, word);
  });

  $status.set('connecting');
  if (config.scenarioId) $scenarioId.set(config.scenarioId);
  if (config.topic) $topic.set(config.topic);
  $sessionStartTime.set(Date.now());

  try {
    ws = new WebSocket(config.backendWsUrl);
  } catch {
    $status.set('error');
    $error.set('Failed to open connection');
    return;
  }

  ws.onopen = () => {
    const baseMsg = config.scenarioId
      ? { type: 'start', scenarioId: config.scenarioId, voiceName: config.voiceName }
      : { type: 'start', topic: config.topic, voiceName: config.voiceName };
    // Phase 2: include preview context for post-call summary generation + optional studentId
    // Batch 5: include storyScript so relay can pass it to buildSystemPrompt
    const startMsg = {
      ...baseMsg,
      ...(config.characterName ? { characterName: config.characterName } : {}),
      ...(config.historicalSetting ? { historicalSetting: config.historicalSetting } : {}),
      ...(config.studentId ? { studentId: config.studentId } : {}),
      ...(config.storyScript ? { storyScript: config.storyScript } : {}),
      ...(config.previewId ? { previewId: config.previewId } : {}),
    };
    ws!.send(JSON.stringify(startMsg));
  };

  ws.onmessage = (event: MessageEvent) => {
    let msg: Record<string, unknown>;
    try {
      msg = JSON.parse(typeof event.data === 'string' ? event.data : '') as Record<string, unknown>;
    } catch {
      return;
    }
    handleServerMessage(msg);
  };

  ws.onerror = () => {
    $error.set('Connection error');
    $status.set('error');
  };

  ws.onclose = makeCloseHandler();
}

/**
 * Creates an onclose handler that implements the retry-or-error logic.
 * Extracted as a factory so resumed WS connections can reuse the same behavior.
 */
function makeCloseHandler(): (event: CloseEvent) => void {
  return (event: CloseEvent) => {
    ws = null;
    clearAudioQueue();

    const currentStatus = $status.get();
    // If session already ended gracefully, nothing to do
    if (currentStatus === 'ended') return;

    const currentSessionId = $sessionId.get();

    // Clean close (code 1000) or no session — give a grace window then error.
    // Grace period: TCP close often races the `ended` JSON message.
    if (!currentSessionId || event.code === 1000) {
      const graceMs = event.wasClean ? 500 : 150;
      setTimeout(() => {
        if ($status.get() === 'ended') return;
        $error.set(event.wasClean ? 'Connection closed' : 'Connection lost');
        $status.set('error');
      }, graceMs);
      return;
    }

    // Unexpected disconnect with an active session — attempt auto-resume
    if (retryAttempt >= RETRY_DELAYS.length) {
      $error.set('Connection lost');
      $status.set('error');
      return;
    }

    $status.set('reconnecting');
    const delay = RETRY_DELAYS[retryAttempt];
    retryAttempt++;

    setTimeout(() => {
      // Re-check: session may have ended during the delay window
      if ($status.get() === 'ended') return;
      attemptResume(currentSessionId);
    }, delay);
  };
}

// ─── Resume (auto-retry after unexpected disconnect) ──────────────────────────

/**
 * Attempts to resume an existing session after an unexpected WS disconnect.
 * Opens a new WS connection and sends `{ type: 'resume', sessionId }`.
 *
 * On `reconnected`: resets retryAttempt, re-wires handlers, sets status to 'active'.
 * On `ended`: processes normally (session expired or timed out on server).
 * On close/error: escalates to next retry or final error state.
 *
 * @why - The server keeps the Gemini relay alive for 180s after browser disconnect.
 *   The `resume` message reattaches the browser to the existing relay session
 *   without restarting the model, preserving full conversation context.
 */
function attemptResume(sessionId: string): void {
  const config = lastConfig;
  if (!config) {
    $error.set('Connection lost');
    $status.set('error');
    return;
  }

  let resumeWs: WebSocket;
  try {
    resumeWs = new WebSocket(config.backendWsUrl);
  } catch {
    escalateRetry(sessionId);
    return;
  }

  let attached = false;

  resumeWs.onopen = () => {
    resumeWs.send(JSON.stringify({ type: 'resume', sessionId }));
  };

  resumeWs.onmessage = (event: MessageEvent) => {
    let msg: Record<string, unknown>;
    try {
      msg = JSON.parse(typeof event.data === 'string' ? event.data : '') as Record<string, unknown>;
    } catch {
      return;
    }

    if (msg['type'] === 'reconnected') {
      // Successfully reattached — take ownership of this WS for the session
      attached = true;
      ws = resumeWs;
      retryAttempt = 0;
      // Re-wire all handlers so this WS behaves like the original session WS
      resumeWs.onmessage = (e: MessageEvent) => {
        let m: Record<string, unknown>;
        try {
          m = JSON.parse(typeof e.data === 'string' ? e.data : '') as Record<string, unknown>;
        } catch {
          return;
        }
        handleServerMessage(m);
      };
      resumeWs.onerror = () => {
        $error.set('Connection error');
        $status.set('error');
      };
      resumeWs.onclose = makeCloseHandler();
      handleServerMessage(msg);
    } else if (msg['type'] === 'ended') {
      // Session expired server-side — process ended normally
      attached = true;
      handleServerMessage(msg);
    }
  };

  resumeWs.onerror = () => {
    if (!attached) escalateRetry(sessionId);
  };

  resumeWs.onclose = () => {
    if (!attached) escalateRetry(sessionId);
  };
}

/**
 * Schedules the next retry attempt or escalates to error state when max attempts reached.
 */
function escalateRetry(sessionId: string): void {
  if (retryAttempt >= RETRY_DELAYS.length) {
    $error.set('Connection lost');
    $status.set('error');
    return;
  }
  const delay = RETRY_DELAYS[retryAttempt];
  retryAttempt++;
  setTimeout(() => {
    if ($status.get() === 'ended') return;
    attemptResume(sessionId);
  }, delay);
}

// ─── Message dispatch ─────────────────────────────────────────────────────────

function handleServerMessage(msg: Record<string, unknown>): void {
  const type = msg['type'];

  switch (type) {
    case 'connected': {
      const connectedSessionId = typeof msg['sessionId'] === 'string' ? msg['sessionId'] : '';
      $sessionId.set(connectedSessionId);
      $status.set('active');
      // Put sessionId in URL so /summary navigation and debug tools can use it
      if (connectedSessionId && typeof window !== 'undefined') {
        const url = new URL(window.location.href);
        url.searchParams.set('session', connectedSessionId);
        window.history.replaceState({}, '', url.toString());
      }
      // Persist session so UI can restore on tab refresh during reconnect
      persistSession({
        sessionId: connectedSessionId,
        characterName: $characterName.get(),
        scenarioId: $scenarioId.get() || undefined,
        topic: $topic.get() || undefined,
        startTime: $sessionStartTime.get(),
      });
      break;
    }

    case 'reconnecting': {
      $status.set('reconnecting');
      // Drop pending words — old speech is gone, new session starts fresh
      clearPacer();
      break;
    }

    case 'reconnected': {
      const reconnectedSessionId = typeof msg['sessionId'] === 'string' ? msg['sessionId'] : '';
      $sessionId.set(reconnectedSessionId);
      $status.set('active');
      addMessage('SYSTEM', '— reconnected —');
      // Update persisted session with new sessionId
      persistSession({
        sessionId: reconnectedSessionId,
        characterName: $characterName.get(),
        scenarioId: $scenarioId.get() || undefined,
        topic: $topic.get() || undefined,
        startTime: $sessionStartTime.get(),
      });
      break;
    }

    case 'audio': {
      if (typeof msg['data'] === 'string') {
        notifyModelSpeaking();
        queueAudio(msg['data']);
      }
      break;
    }

    case 'output_transcription': {
      if (typeof msg['text'] === 'string') {
        const raw = msg['text'];

        // Model is producing new output — safe to play audio again
        unsuppressAudioDebounced();

        // Suppress stale chunks following an interruption (ghost text fix)
        if (suppressTranscriptionCount > 0) {
          suppressTranscriptionCount--;
          break;
        }

        // Strip noise tokens and thinking text leaks from Gemini
        const text = sanitizeTranscript(raw);
        if (!text) break;

        // Finalize any pending student turn — character is now speaking
        finalizeInputTurn();

        // Backward compat: still update $outputTranscript
        appendOutputTranscript(text);

        // Paced reveal: buffer words, drip at 138 WPM (435ms/word)
        // Pacer callback calls addMessage(characterName, word) per drip
        enqueueWords(text);
      }
      break;
    }

    case 'input_transcription': {
      if (typeof msg['text'] === 'string') {
        const raw = msg['text'];
        // Student is speaking — suppress stale model audio immediately
        suppressAudio();
        // Strip noise tokens from student's transcription
        const text = sanitizeTranscript(raw);
        if (!text) break;

        if (useWebSpeechForDisplay) {
          // Web Speech API handles user-facing display — Gemini transcription is
          // server-side logging only. Still update $inputTranscript for post-call summary.
          // (trackInputTurn / addMessage handled in Web Speech callback above)
          $inputTranscript.set(raw); // raw text for server-side logging transcript store
        } else {
          // Web Speech unavailable — fall back to Gemini's input_transcription for display
          trackInputTurn(text);
          $inputTranscript.set(getInputTranscript());
          addMessage('YOU', text);
          if ($activeChoices.get()) $activeChoices.set(null);
        }
      }
      break;
    }

    case 'speaker_switch': {
      const name = (msg as { name?: string }).name;
      if (name) $characterName.set(name);
      break;
    }

    case 'choices': {
      const choices = (msg as { choices?: { title: string; description: string }[] }).choices;
      if (choices) {
        $activeChoices.set(choices);
        // Resolve storyScript context for setup question + per-option consequences.
        // Used by SessionChoiceCards to record ChoiceEvent on selection.
        const script = $previewData.get()?.storyScript;
        if (script?.choices) {
          const match = script.choices.find((sc) =>
            sc.options.some((opt) => choices.some((c) => c.title === opt.title))
          );
          $activeChoiceContext.set(
            match ? { setup: match.setup, consequences: match.consequences } : null
          );
        } else {
          $activeChoiceContext.set(null);
        }
      }
      break;
    }

    case 'scene_image_loading': {
      const loadingTitle = msg['title'];
      if (typeof loadingTitle === 'string') {
        $sceneImageLoading.set(loadingTitle);
        $sceneImageFailed.set(null);
      }
      break;
    }

    case 'scene_image': {
      const title = msg['title'];
      const image = msg['image'];
      if (typeof title === 'string' && typeof image === 'string') {
        $sceneImageLoading.set(null);
        $sceneImageFailed.set(null);
        const scenePayload = { title, image };
        $sceneImage.set(scenePayload);
        $sceneImages.set([...$sceneImages.get(), scenePayload]);
      }
      break;
    }

    case 'scene_image_failed': {
      const failedTitle = msg['title'];
      $sceneImageLoading.set(null);
      $sceneImageFailed.set(typeof failedTitle === 'string' ? failedTitle : 'scene');
      break;
    }

    case 'turn_complete': {
      // Flush any remaining buffered words to display immediately
      flushAll();
      finalizeInputTurn();
      break;
    }

    case 'interrupted': {
      // Suppress next 1-2 output_transcription events — they're already-spoken stale chunks
      suppressTranscriptionCount = 2;
      clearPacer(); // Drop pending words — they're from the interrupted speech
      clearAudioQueue();
      $isSpeaking.set(false);
      break;
    }

    case 'ended': {
      stopWebSpeechTranscription();
      useWebSpeechForDisplay = false;
      clearAudioQueue();
      $activeChoices.set(null);
      clearPersistedSession();
      const durationMs = Date.now() - $sessionStartTime.get();

      // Phase 2: prefer server-generated summary when present
      const serverSummary = msg['summary'] as {
        keyFacts: string[];
        outcomeComparison: string;
        characterMessage: string;
        suggestedCalls: { name: string; era: string; hook: string }[];
      } | undefined;

      if (serverSummary) {
        createSummaryFromServer({ serverSummary, durationMs });
      } else {
        // Phase 1 fallback: hardcoded scenario metadata
        createSummaryArtifact({
          scenarioId: $scenarioId.get(),
          topic: $topic.get(),
          durationMs,
        });
      }

      $status.set('ended');
      break;
    }

    case 'error': {
      $error.set(typeof msg['message'] === 'string' ? msg['message'] : 'Unknown error');
      $status.set('error');
      break;
    }
  }
}

// ─── Send helpers ─────────────────────────────────────────────────────────────

export function sendAudio(base64Data: string): void {
  if (!ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify({ type: 'audio', data: base64Data, mimeType: 'audio/pcm;rate=16000' }));
}

export function sendText(text: string): void {
  if (!ws || ws.readyState !== WebSocket.OPEN) return;
  addMessage('YOU', text);
  // Text input is a complete utterance (not cumulative) — track as a full turn
  trackInputTurn(text);
  finalizeInputTurn();
  $inputTranscript.set(getInputTranscript());
  ws.send(JSON.stringify({ type: 'text', text }));
}

export function sendAudioEnd(): void {
  if (!ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify({ type: 'audio_end' }));
}

export function disconnect(): void {
  if (ws) {
    ws.close();
    ws = null;
  }
  clearAudioQueue();
  stopWebSpeechTranscription();
  useWebSpeechForDisplay = false;
}
