/**
 * @what - Zod schemas for all Flash JSON responses parsed by this server
 * @why - Single source of truth for response shapes; eliminates per-file manual type checking
 * @exports - postCallSummarySchema, previewMetadataSchema, figureCardSchema, flashResponseSchema + inferred types
 */

import { z } from 'zod';

// ─── Post-call summary ────────────────────────────────────────────────────────

export const postCallSummarySchema = z.object({
  /** 3-8 key historical facts discussed during the call, written in the character's voice. */
  keyFacts: z.array(z.string()),
  /** How the student's advice/choices compare to what actually happened historically. */
  outcomeComparison: z.string(),
  /** Character's farewell message — positive observation about the student, written IN CHARACTER. */
  characterMessage: z.string(),
  /** 3 related historical figures to call next. */
  suggestedCalls: z.array(
    z.object({
      name: z.string(),
      era: z.string(),
      hook: z.string(),
    }),
  ),
});

export type PostCallSummary = z.infer<typeof postCallSummarySchema>;

// ─── Session preview metadata ─────────────────────────────────────────────────

export const previewMetadataSchema = z.object({
  topic: z.string(),
  /**
   * How the character would describe the stranger who called them.
   * NOT a student role — the student has no assigned role.
   * e.g. "A stranger who called in the dead of night"
   */
  userRole: z.string(),
  characterName: z.string(),
  historicalSetting: z.string(),
  year: z.number(),
  context: z.string(),
  /** 5 OKLCH values defining the era color palette. */
  colorPalette: z.array(z.string()).length(5),
  /** Voice name from the 30-voice catalog, selected by Flash. */
  voiceName: z.string(),
  /** 2-3 key decision moments for announce_choice. */
  decisionPoints: z.array(
    z.object({
      title: z.string(),
      description: z.string(),
    }),
  ),
});

export type PreviewMetadata = z.infer<typeof previewMetadataSchema>;

// ─── Story script (bag-of-material architecture) ──────────────────────────────

export const personalitySchema = z.object({
  /** How the character speaks — tone, register, word choice. */
  voice: z.string(),
  /** The humor MECHANISM, not "be funny" — e.g. "understatement of absurd facts". */
  humor: z.string(),
  /** 1-2 verbal habits or recurring attitudes unique to this character. */
  quirks: z.string(),
  /** Emotional register — how they carry themselves. */
  energy: z.string(),
  /**
   * Real comedian/celebrity whose DELIVERY STYLE to channel.
   * Gives the model an instant voice register instead of vague adjectives.
   * e.g. "Jennifer Coolidge playing a pharaoh", "Dave Chappelle as a general"
   */
  celebrityAnchor: z.string(),
});

export const hookSchema = z.object({
  /** Common misconception about this character or moment. */
  myth: z.string(),
  /** The real story — must be more interesting than the myth. */
  truth: z.string(),
  /** The "wait, WHAT?" moment — the detail that makes students lean forward. */
  surprise: z.string(),
  /** Universal connection — group projects, sports, family — never academic. */
  anchor: z.string(),
});

export const choiceOptionSchema = z.object({
  title: z.string(),
  description: z.string(),
});

export const choiceSchema = z.object({
  /** Scene-setting for the dilemma — what moment is the student stepping into. */
  setup: z.string(),
  /** 2-3 derivable options, no wrong answer, each teaches a different facet. */
  options: z.array(choiceOptionSchema).min(2).max(3),
  /**
   * Per-option consequences keyed by option title.
   * e.g. { "Flee to Egypt": "That is what she did — on a ship before his body was cold." }
   */
  consequences: z.record(z.string(), z.string()),
});

export const sceneSchema = z.object({
  /** Short label used to trigger the right scene via show_scene. */
  title: z.string(),
  /** Visual description for Gemini 3.1 Image to render mid-call. */
  description: z.string(),
});

/**
 * Bag-of-material structure generated by Flash per character.
 *
 * @inference - Flash fills the bag; Gemini Live performs from it.
 *   No linear script — character pulls hooks/facts/choices based on
 *   where the student takes the conversation.
 *
 * @pitfall - `hooks` min(3) is enforced. Flash must return at least 3
 *   myth/truth combos to give the character enough material to vary.
 */
export const storyScriptSchema = z.object({
  personality: personalitySchema,
  /** 3-5 myth/truth/surprise/anchor combos — the "wait WHAT?" moments. */
  hooks: z.array(hookSchema).min(3).max(5),
  /** Verified historical details — woven in one at a time, never dumped. */
  facts: z.array(z.string()).min(5).max(10),
  /** 1-2 derivable dilemmas presented via announce_choice at natural moments. */
  choices: z.array(choiceSchema).min(1).max(2),
  /** 1-3 visual descriptions used when show_scene fires. */
  scenes: z.array(sceneSchema).min(1).max(3),
  /** Final reframe line — character's specific observation about the student. */
  closingThread: z.string(),
});

export type StoryScript = z.infer<typeof storyScriptSchema>;

// ─── Figure card (topic → 3 related historical figures) ──────────────────────

/**
 * A historical figure card returned when a topic is submitted.
 * Used in both /extract-topic (image) and /session-preview (text/voice) flows.
 * Three cards are always returned — student picks one to start the call.
 */
export const figureCardSchema = z.object({
  /** Full historical name (e.g. "Marcus Vitruvius Pollio") */
  name: z.string(),
  /** Era/period in one short phrase (e.g. "Roman Empire, 1st century BC") */
  era: z.string(),
  /** Role or occupation in the context of the topic (e.g. "Architect & Engineer") */
  role: z.string(),
  /** One-line hook — what makes this person interesting to call (e.g. "Wrote the only surviving ancient architecture manual") */
  teaser: z.string(),
  /** Why this person is specifically relevant to the extracted topic */
  relevance_to_topic: z.string(),
});

export type FigureCard = z.infer<typeof figureCardSchema>;

// ─── Extract-topic response ───────────────────────────────────────────────────

/**
 * Response from /extract-topic — includes extracted topic text AND 3 figure cards.
 * Flash vision extracts the topic from the image, then immediately suggests who to call.
 */
export const extractTopicResponseSchema = z.object({
  /** Short topic phrase extracted from the image (e.g. "Roman art & architecture") */
  topic_extracted: z.string(),
  /** 3 historical figures related to the topic — student picks one to call */
  figures: z.array(figureCardSchema).length(3),
});

export type ExtractTopicResponse = z.infer<typeof extractTopicResponseSchema>;

// ─── Flash discriminated union ────────────────────────────────────────────────

/**
 * Flash returns one of two response types: ready or blocked.
 *
 * ANY topic input (person, event, era, concept) → "ready" with full metadata.
 * Flash picks the single most compelling historical figure who lived through it.
 *
 * @inference - Discriminated on `type` literal — TypeScript narrows correctly after
 *   checking `result.data.type`. No casting needed downstream.
 */
export const flashResponseSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('ready'),
    metadata: previewMetadataSchema,
    /**
     * Bag-of-material generated by Flash for this character.
     * Optional for backward compatibility with preset fallbacks
     * (presets will be migrated to storyScript in Batch 2).
     */
    storyScript: storyScriptSchema.optional(),
  }),
  z.object({
    type: z.literal('blocked'),
    alternatives: z.array(
      z.object({
        title: z.string(),
        description: z.string(),
      }),
    ),
  }),
]);

export type FlashResponse = z.infer<typeof flashResponseSchema>;
